import random


def guess(x):
    """
    let the user guess the random number generated by the computer
    Args:
        x: the upper bound of the random number
    Returns: none
    """
    # randomly generate a number in [1,x]
    random_num = random.randint(1, x)
    # initial guess to be 0
    guess = 0
    # continue the loop until the user guess the correct number
    while guess != random_num:
        # ask user to guess a number
        guess = int(input(f"Guess a number between 1 and {x}: "))
        if guess < random_num:
            print("Sorry, guess again. Too low.")
        elif guess > random_num:
            print("Sorry, guess again. Too high.")

    print(f"Yay, congrats. You have guessed the number {random_num} correctly")


def computer_guess():
    """
    let the computer guess the correct integer number based on user's feedback
    feedback: c = correct, h = high, l = low

    Args:
        x: the upper bound of the number

    Returns: None

    """
    # lower bound
    low = 1
    # upper bound of guess range
    high = int(input("You want the computer to guess a number between 1 and ?? (please enter an integer): "))
    feedback = ''
    # keep guessing until the user feedback correct(c)
    while feedback != 'c':
        if low != high:
            #guess = random.randint(low, high)
            guess = round((low + high)/2)
        # if the lower bound = upper bound, then the correct number = lower bound = upper bound
        else:
            guess = low
        feedback = input(f"Is {guess} too high (H), too low(L), or correct (C)?").lower()
        # if the user says the number is too high, our upper bound will decrease 1
        if feedback == "h":
            high = guess - 1
        # if the user says the number is too low, our lower bound will increase 1
        elif feedback == "l":
            low = guess + 1

    print(f"Yay! The computer guessed your number, {guess}, correctly!")


if __name__ == "__main__":
    guess(10)
    computer_guess()
